name: Build & Deploy

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 3 * * *' # every day at 3am UTC

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NUXT_PUBLIC_STUDIO_TOKENS: ${{secrets.NUXT_PUBLIC_STUDIO_TOKENS}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing packages
        run: npm ci

      - name: Build Nuxt 3 static site
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'Automatic deploy: ${{ github.event.head_commit.message }}'
