name: Sync Notion
on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run notion-sync
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Notion Sync